

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * People generated by hbm2java
 */
public class People implements java.io.Serializable {

   private String email_address;
   private String name;
   private String username;
   private String top_level_domain;

   public People() {
   }

   public People(String email_address, String name, String username, String top_level_domain)
   {
      this.email_address = email_address;
      this.name = name;
      this.username = username;
      this.top_level_domain = top_level_domain;
   }

   public String getEmail_address()
   {
      return email_address;
   }

   public void setEmail_address(String email_address)
   {
      this.email_address = email_address;
   }

   public String getName()
   {
      return name;
   }

   public void setName(String name)
   {
      this.name = name;
   }

   public String getUsername()
   {
      return username;
   }

   public void setUsername(String username)
   {
      this.username = username;
   }

   public String getTop_level_domain()
   {
      return top_level_domain;
   }

   public void setTop_level_domain(String top_level_domain)
   {
      this.top_level_domain = top_level_domain;
   }
   
}
