package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * People generated by hbm2java
 */
public class People implements java.io.Serializable {

   private String email_address;
   private String name;
   private String username;
   private String top_level_domain;

   public People() {
   }

   public People(String email_address, String name, String username, String top_level_domain)
   {
      this.email_address = email_address;
      this.name = name;
      this.username = username;
      this.top_level_domain = top_level_domain;
   }
   
}
