package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Attachments generated by hbm2java
 */
public class Attachments implements java.io.Serializable {

	private Integer id;
	private int issueId;
	private String name;
	private String description;
	private String url;
	private Integer submittedBy;
	private Date submittedOn;

	public Attachments() {
	}

	public Attachments(int issueId, String name, String description, String url) {
		this.issueId = issueId;
		this.name = name;
		this.description = description;
		this.url = url;
	}

	public Attachments(int issueId, String name, String description,
			String url, Integer submittedBy, Date submittedOn) {
		this.issueId = issueId;
		this.name = name;
		this.description = description;
		this.url = url;
		this.submittedBy = submittedBy;
		this.submittedOn = submittedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Integer getSubmittedBy() {
		return this.submittedBy;
	}

	public void setSubmittedBy(Integer submittedBy) {
		this.submittedBy = submittedBy;
	}

	public Date getSubmittedOn() {
		return this.submittedOn;
	}

	public void setSubmittedOn(Date submittedOn) {
		this.submittedOn = submittedOn;
	}

}
