package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Changes generated by hbm2java
 */
public class Changes implements java.io.Serializable {

	private Integer id;
	private int issueId;
	private String field;
	private String oldValue;
	private String newValue;
	private int changedBy;
	private Date changedOn;

	public Changes() {
	}

	public Changes(int issueId, String field, String oldValue, String newValue,
			int changedBy, Date changedOn) {
		this.issueId = issueId;
		this.field = field;
		this.oldValue = oldValue;
		this.newValue = newValue;
		this.changedBy = changedBy;
		this.changedOn = changedOn;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	public String getOldValue() {
		return this.oldValue;
	}

	public void setOldValue(String oldValue) {
		this.oldValue = oldValue;
	}

	public String getNewValue() {
		return this.newValue;
	}

	public void setNewValue(String newValue) {
		this.newValue = newValue;
	}

	public int getChangedBy() {
		return this.changedBy;
	}

	public void setChangedBy(int changedBy) {
		this.changedBy = changedBy;
	}

	public Date getChangedOn() {
		return this.changedOn;
	}

	public void setChangedOn(Date changedOn) {
		this.changedOn = changedOn;
	}

}
