package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * IssuesWatchers generated by hbm2java
 */
public class IssuesWatchers implements java.io.Serializable {

	private Integer id;
	private int issueId;
	private int personId;

	public IssuesWatchers() {
	}

	public IssuesWatchers(int issueId, int personId) {
		this.issueId = issueId;
		this.personId = personId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public int getPersonId() {
		return this.personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

}
