package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Issues generated by hbm2java
 */
public class Issues implements java.io.Serializable {

	private Integer id;
	private int trackerId;
	private String issue;
	private String type;
	private String summary;
	private String description;
	private String status;
	private String resolution;
	private String priority;
	private int submittedBy;
	private Date submittedOn;
	private int assignedTo;

	public Issues() {
	}

	public Issues(int trackerId, String issue, String summary,
			String description, String status, int submittedBy,
			Date submittedOn, int assignedTo) {
		this.trackerId = trackerId;
		this.issue = issue;
		this.summary = summary;
		this.description = description;
		this.status = status;
		this.submittedBy = submittedBy;
		this.submittedOn = submittedOn;
		this.assignedTo = assignedTo;
	}

	public Issues(int trackerId, String issue, String type, String summary,
			String description, String status, String resolution,
			String priority, int submittedBy, Date submittedOn, int assignedTo) {
		this.trackerId = trackerId;
		this.issue = issue;
		this.type = type;
		this.summary = summary;
		this.description = description;
		this.status = status;
		this.resolution = resolution;
		this.priority = priority;
		this.submittedBy = submittedBy;
		this.submittedOn = submittedOn;
		this.assignedTo = assignedTo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getResolution() {
		return this.resolution;
	}

	public void setResolution(String resolution) {
		this.resolution = resolution;
	}

	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	public int getSubmittedBy() {
		return this.submittedBy;
	}

	public void setSubmittedBy(int submittedBy) {
		this.submittedBy = submittedBy;
	}

	public Date getSubmittedOn() {
		return this.submittedOn;
	}

	public void setSubmittedOn(Date submittedOn) {
		this.submittedOn = submittedOn;
	}

	public int getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(int assignedTo) {
		this.assignedTo = assignedTo;
	}

}
