package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * People generated by hbm2java
 */
public class People implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String userId;
	private int trackerId;

	public People() {
	}

	public People(String userId, int trackerId) {
		this.userId = userId;
		this.trackerId = trackerId;
	}

	public People(String name, String email, String userId, int trackerId) {
		this.name = name;
		this.email = email;
		this.userId = userId;
		this.trackerId = trackerId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getTrackerId() {
		return this.trackerId;
	}

	public void setTrackerId(int trackerId) {
		this.trackerId = trackerId;
	}

}
