package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * RelatedTo generated by hbm2java
 */
public class RelatedTo implements java.io.Serializable {

	private Integer id;
	private int issueId;
	private int relatedTo;
	private String type;

	public RelatedTo() {
	}

	public RelatedTo(int issueId, int relatedTo, String type) {
		this.issueId = issueId;
		this.relatedTo = relatedTo;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getIssueId() {
		return this.issueId;
	}

	public void setIssueId(int issueId) {
		this.issueId = issueId;
	}

	public int getRelatedTo() {
		return this.relatedTo;
	}

	public void setRelatedTo(int relatedTo) {
		this.relatedTo = relatedTo;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
