package bicho;

// Generated Apr 27, 2013 2:06:40 PM by Hibernate Tools 3.4.0.CR1

/**
 * SupportedTrackers generated by hbm2java
 */
public class SupportedTrackers implements java.io.Serializable {

	private Integer id;
	private String version;
	private String name;

	public SupportedTrackers() {
	}

	public SupportedTrackers(String name) {
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
