package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * ActionFiles generated by hbm2java
 */
public class ActionFiles implements java.io.Serializable {

	private ActionFilesId id;

	public ActionFiles() {
	}

	public ActionFiles(ActionFilesId id) {
		this.id = id;
	}

	public ActionFilesId getId() {
		return this.id;
	}

	public void setId(ActionFilesId id) {
		this.id = id;
	}

}
