package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * ActionsFileNamesId generated by hbm2java
 */
public class ActionsFileNamesId implements java.io.Serializable {

	private int id;
	private String type;
	private Integer fileId;
	private String newFileName;
	private Integer commitId;

	public ActionsFileNamesId() {
	}

	public ActionsFileNamesId(int id) {
		this.id = id;
	}

	public ActionsFileNamesId(int id, String type, Integer fileId,
			String newFileName, Integer commitId) {
		this.id = id;
		this.type = type;
		this.fileId = fileId;
		this.newFileName = newFileName;
		this.commitId = commitId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getNewFileName() {
		return this.newFileName;
	}

	public void setNewFileName(String newFileName) {
		this.newFileName = newFileName;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActionsFileNamesId))
			return false;
		ActionsFileNamesId castOther = (ActionsFileNamesId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getFileId() == castOther.getFileId()) || (this
						.getFileId() != null && castOther.getFileId() != null && this
						.getFileId().equals(castOther.getFileId())))
				&& ((this.getNewFileName() == castOther.getNewFileName()) || (this
						.getNewFileName() != null
						&& castOther.getNewFileName() != null && this
						.getNewFileName().equals(castOther.getNewFileName())))
				&& ((this.getCommitId() == castOther.getCommitId()) || (this
						.getCommitId() != null
						&& castOther.getCommitId() != null && this
						.getCommitId().equals(castOther.getCommitId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getFileId() == null ? 0 : this.getFileId().hashCode());
		result = 37
				* result
				+ (getNewFileName() == null ? 0 : this.getNewFileName()
						.hashCode());
		result = 37 * result
				+ (getCommitId() == null ? 0 : this.getCommitId().hashCode());
		return result;
	}

}
