package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * ActionFilesId generated by hbm2java
 */
public class ActionFilesId implements java.io.Serializable {

	private Integer fileId;
	private int actionId;
	private String actionType;
	private Integer commitId;

	public ActionFilesId() {
	}

	public ActionFilesId(int actionId) {
		this.actionId = actionId;
	}

	public ActionFilesId(Integer fileId, int actionId, String actionType,
			Integer commitId) {
		this.fileId = fileId;
		this.actionId = actionId;
		this.actionType = actionType;
		this.commitId = commitId;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public int getActionId() {
		return this.actionId;
	}

	public void setActionId(int actionId) {
		this.actionId = actionId;
	}

	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ActionFilesId))
			return false;
		ActionFilesId castOther = (ActionFilesId) other;

		return ((this.getFileId() == castOther.getFileId()) || (this
				.getFileId() != null && castOther.getFileId() != null && this
				.getFileId().equals(castOther.getFileId())))
				&& (this.getActionId() == castOther.getActionId())
				&& ((this.getActionType() == castOther.getActionType()) || (this
						.getActionType() != null
						&& castOther.getActionType() != null && this
						.getActionType().equals(castOther.getActionType())))
				&& ((this.getCommitId() == castOther.getCommitId()) || (this
						.getCommitId() != null
						&& castOther.getCommitId() != null && this
						.getCommitId().equals(castOther.getCommitId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFileId() == null ? 0 : this.getFileId().hashCode());
		result = 37 * result + this.getActionId();
		result = 37
				* result
				+ (getActionType() == null ? 0 : this.getActionType()
						.hashCode());
		result = 37 * result
				+ (getCommitId() == null ? 0 : this.getCommitId().hashCode());
		return result;
	}

}
