package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * ActionsFileNames generated by hbm2java
 */
public class ActionsFileNames implements java.io.Serializable {

	private ActionsFileNamesId id;

	public ActionsFileNames() {
	}

	public ActionsFileNames(ActionsFileNamesId id) {
		this.id = id;
	}

	public ActionsFileNamesId getId() {
		return this.id;
	}

	public void setId(ActionsFileNamesId id) {
		this.id = id;
	}

}
