package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * Files generated by hbm2java
 */
public class Files implements java.io.Serializable {

	private int id;
	private String fileName;
	private Integer repositoryId;

	public Files() {
	}

	public Files(int id) {
		this.id = id;
	}

	public Files(int id, String fileName, Integer repositoryId) {
		this.id = id;
		this.fileName = fileName;
		this.repositoryId = repositoryId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Integer getRepositoryId() {
		return this.repositoryId;
	}

	public void setRepositoryId(Integer repositoryId) {
		this.repositoryId = repositoryId;
	}

}
