package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * FileTypes generated by hbm2java
 */
public class FileTypes implements java.io.Serializable {

	private int id;
	private Integer fileId;
	private String type;

	public FileTypes() {
	}

	public FileTypes(int id) {
		this.id = id;
	}

	public FileTypes(int id, Integer fileId, String type) {
		this.id = id;
		this.fileId = fileId;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
