package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * FileLinks generated by hbm2java
 */
public class FileLinks implements java.io.Serializable {

	private int id;
	private Integer parentId;
	private Integer fileId;
	private Integer commitId;
	private String filePath;

	public FileLinks() {
	}

	public FileLinks(int id) {
		this.id = id;
	}

	public FileLinks(int id, Integer parentId, Integer fileId,
			Integer commitId, String filePath) {
		this.id = id;
		this.parentId = parentId;
		this.fileId = fileId;
		this.commitId = commitId;
		this.filePath = filePath;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public String getFilePath() {
		return this.filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}

}
