package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private int id;
	private Integer fileId;
	private Integer commitId;
	private String lang;
	private Integer sloc;
	private Integer loc;
	private Integer ncomment;
	private Integer lcomment;
	private Integer lblank;
	private Integer nfunctions;
	private Integer mccabeMax;
	private Integer mccabeMin;
	private Integer mccabeSum;
	private Integer mccabeMean;
	private Integer mccabeMedian;
	private Integer halsteadLength;
	private Integer halsteadVol;
	private Double halsteadLevel;
	private Integer halsteadMd;

	public Metrics() {
	}

	public Metrics(int id) {
		this.id = id;
	}

	public Metrics(int id, Integer fileId, Integer commitId, String lang,
			Integer sloc, Integer loc, Integer ncomment, Integer lcomment,
			Integer lblank, Integer nfunctions, Integer mccabeMax,
			Integer mccabeMin, Integer mccabeSum, Integer mccabeMean,
			Integer mccabeMedian, Integer halsteadLength, Integer halsteadVol,
			Double halsteadLevel, Integer halsteadMd) {
		this.id = id;
		this.fileId = fileId;
		this.commitId = commitId;
		this.lang = lang;
		this.sloc = sloc;
		this.loc = loc;
		this.ncomment = ncomment;
		this.lcomment = lcomment;
		this.lblank = lblank;
		this.nfunctions = nfunctions;
		this.mccabeMax = mccabeMax;
		this.mccabeMin = mccabeMin;
		this.mccabeSum = mccabeSum;
		this.mccabeMean = mccabeMean;
		this.mccabeMedian = mccabeMedian;
		this.halsteadLength = halsteadLength;
		this.halsteadVol = halsteadVol;
		this.halsteadLevel = halsteadLevel;
		this.halsteadMd = halsteadMd;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getFileId() {
		return this.fileId;
	}

	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

	public String getLang() {
		return this.lang;
	}

	public void setLang(String lang) {
		this.lang = lang;
	}

	public Integer getSloc() {
		return this.sloc;
	}

	public void setSloc(Integer sloc) {
		this.sloc = sloc;
	}

	public Integer getLoc() {
		return this.loc;
	}

	public void setLoc(Integer loc) {
		this.loc = loc;
	}

	public Integer getNcomment() {
		return this.ncomment;
	}

	public void setNcomment(Integer ncomment) {
		this.ncomment = ncomment;
	}

	public Integer getLcomment() {
		return this.lcomment;
	}

	public void setLcomment(Integer lcomment) {
		this.lcomment = lcomment;
	}

	public Integer getLblank() {
		return this.lblank;
	}

	public void setLblank(Integer lblank) {
		this.lblank = lblank;
	}

	public Integer getNfunctions() {
		return this.nfunctions;
	}

	public void setNfunctions(Integer nfunctions) {
		this.nfunctions = nfunctions;
	}

	public Integer getMccabeMax() {
		return this.mccabeMax;
	}

	public void setMccabeMax(Integer mccabeMax) {
		this.mccabeMax = mccabeMax;
	}

	public Integer getMccabeMin() {
		return this.mccabeMin;
	}

	public void setMccabeMin(Integer mccabeMin) {
		this.mccabeMin = mccabeMin;
	}

	public Integer getMccabeSum() {
		return this.mccabeSum;
	}

	public void setMccabeSum(Integer mccabeSum) {
		this.mccabeSum = mccabeSum;
	}

	public Integer getMccabeMean() {
		return this.mccabeMean;
	}

	public void setMccabeMean(Integer mccabeMean) {
		this.mccabeMean = mccabeMean;
	}

	public Integer getMccabeMedian() {
		return this.mccabeMedian;
	}

	public void setMccabeMedian(Integer mccabeMedian) {
		this.mccabeMedian = mccabeMedian;
	}

	public Integer getHalsteadLength() {
		return this.halsteadLength;
	}

	public void setHalsteadLength(Integer halsteadLength) {
		this.halsteadLength = halsteadLength;
	}

	public Integer getHalsteadVol() {
		return this.halsteadVol;
	}

	public void setHalsteadVol(Integer halsteadVol) {
		this.halsteadVol = halsteadVol;
	}

	public Double getHalsteadLevel() {
		return this.halsteadLevel;
	}

	public void setHalsteadLevel(Double halsteadLevel) {
		this.halsteadLevel = halsteadLevel;
	}

	public Integer getHalsteadMd() {
		return this.halsteadMd;
	}

	public void setHalsteadMd(Integer halsteadMd) {
		this.halsteadMd = halsteadMd;
	}

}
