package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * Repositories generated by hbm2java
 */
public class Repositories implements java.io.Serializable {

	private int id;
	private String uri;
	private String name;
	private String type;

	public Repositories() {
	}

	public Repositories(int id) {
		this.id = id;
	}

	public Repositories(int id, String uri, String name, String type) {
		this.id = id;
		this.uri = uri;
		this.name = name;
		this.type = type;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
