package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Scmlog generated by hbm2java
 */
public class Scmlog implements java.io.Serializable {

	private int id;
	private String rev;
	private Integer committerId;
	private Integer authorId;
	private Date date;
	private String message;
	private Boolean composedRev;
	private Integer repositoryId;

	public Scmlog() {
	}

	public Scmlog(int id) {
		this.id = id;
	}

	public Scmlog(int id, String rev, Integer committerId, Integer authorId,
			Date date, String message, Boolean composedRev, Integer repositoryId) {
		this.id = id;
		this.rev = rev;
		this.committerId = committerId;
		this.authorId = authorId;
		this.date = date;
		this.message = message;
		this.composedRev = composedRev;
		this.repositoryId = repositoryId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRev() {
		return this.rev;
	}

	public void setRev(String rev) {
		this.rev = rev;
	}

	public Integer getCommitterId() {
		return this.committerId;
	}

	public void setCommitterId(Integer committerId) {
		this.committerId = committerId;
	}

	public Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(Integer authorId) {
		this.authorId = authorId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public Boolean getComposedRev() {
		return this.composedRev;
	}

	public void setComposedRev(Boolean composedRev) {
		this.composedRev = composedRev;
	}

	public Integer getRepositoryId() {
		return this.repositoryId;
	}

	public void setRepositoryId(Integer repositoryId) {
		this.repositoryId = repositoryId;
	}

}
