package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * TagRevisions generated by hbm2java
 */
public class TagRevisions implements java.io.Serializable {

	private int id;
	private Integer tagId;
	private Integer commitId;

	public TagRevisions() {
	}

	public TagRevisions(int id) {
		this.id = id;
	}

	public TagRevisions(int id, Integer tagId, Integer commitId) {
		this.id = id;
		this.tagId = tagId;
		this.commitId = commitId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public Integer getCommitId() {
		return this.commitId;
	}

	public void setCommitId(Integer commitId) {
		this.commitId = commitId;
	}

}
