package cvsanaly;

// Generated Apr 27, 2013 2:07:58 PM by Hibernate Tools 4.0.0

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private int id;
	private String name;

	public Tags() {
	}

	public Tags(int id) {
		this.id = id;
	}

	public Tags(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
